# Generated by Django 4.0.3 on 2022-04-02 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
