# Generated by Django 4.0.3 on 2022-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_photo_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Приватный ли'),
        ),
    ]
