# Generated by Django 4.0.3 on 2022-04-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_album_favorites_alter_photo_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.CharField(default=None, max_length=45, null=True, unique=True, verbose_name='Токен'),
        ),
    ]
